### ISSUE TITLE
US1 - Add list

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#1]
## Value Proposition

As a user i want to have an overview of
my all my customers and their inventory, 
in order to see how much boxes/buckets
the customers have at their store.

## Description
<img width="192" alt="Bildschirmfoto 2023-07-19 um 10 57 31" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/3d7e12ad-283c-436b-9c09-76fd1f2f3d5e">

​

## Acceptance Criteria
- [x] there should be a list, which shows how much buckets the customers have at their store
- [x] there should be a column for the customer name, the boxes and the buckets
- [x] there should be a header displaying the logo of the company
      ​

## Tasks

- [x] create a branch with a fitting name
- [x] add a seperate Header component for the list view, which shows the logo of the company
- [x] add a list component to the project
- [x] for first add static customer data as an array of customer objects to the list file and put some objects with costumer data(name, boxes, buckets, id)
- [x] in the list component map over the static costumer data and display a list item for every entry

**Comment by actyvystom** [comment]
A nice first one! 👍🏻 
See some comments:
- Concerning your **value proposition**, I guess the word `data` is kind of unnecessarily technical, don't you simply want to have an overview of all your customers and their inventory?
- Some tiny wording in your **acceptance criteria**: I suggest to use `column` instead of `span`
- Some tiny wording in your **tasks** list: concerning your dummy data, I suggest to rewrite it, e.g. _add static customer data as an array of customer objects_
