### ISSUE TITLE
US7 - Add Create functionality

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#17]
## Value Proposition

As a user 
i want to have an interface to add customers
in order to add customers to the database
​

## Description
<img width="248" alt="Bildschirmfoto 2023-07-25 um 14 21 45" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/3b773f22-4483-45b0-a5ea-a61b6dbc970e">

​

## Acceptance Criteria

- [ ] there should be a link in the menu-page which leads to the form to create a customer
- [ ] when the form is submitted, there should be a new customer in the database (and in the list component)
- [ ] the inputs should be required
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] add a menu.js to the project
- [ ] in the menu.js add a "Kunden hinzufügen" Link
- [ ] the link should navigate to the AddCustomer page which you have to create too
- [ ] in the AddCustomer.js should be a form questioning for the name and the adress of the customer
- [ ] the "Hinzufügen" button should send a CREATE request to the database and add the customer to the data
- [ ] set the inputs as required to prevent wrong data-creation

**Comment by ekat-br** [comment]
LGTM
