### ISSUE TITLE
US8 - Add sorted customer list

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#18]
## Value Proposition

As a user
i want to see the customer list in a proper sorted way
in order to see where are the most boxes to pick them up

​

## Description

<img width="139" alt="Bildschirmfoto 2023-07-25 um 14 29 11" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/8408a277-046b-4d99-b852-71361b906cfa">

## Acceptance Criteria

-in the default view the list should be sorted
by how much boxes the customer has
-there should be other options to sort the list to: by name, by buckets
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] in the list component before mapping over the customer data, there should be an array created which is sorted by how much boxes are at the customers store
- [ ] put an onclick function on the headings of the table, which sorts the list in the ways mentioned in the acceptance criteria

**Comment by Miladu93** [comment]
looks good, nice job
