### ISSUE TITLE
US9 - Add a Update functionality

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#19]
## Value Proposition

As a user
i want to search for customers
in order pick one and change its data

## Description
<img width="341" alt="Bildschirmfoto 2023-07-25 um 14 47 44" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/ace7b331-83d7-4dcf-ad3e-ba8f0e298422">

​

## Acceptance Criteria

- [ ] in the menu.js there should be a link which leads to the edit-page
- [ ] the edit page should display a input to search for customers
- [ ] onChange it should search for customers and show them in a dropdown menu, which links to a form
- [ ] in the form you can update the customers name or adress
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] add a link to the menu.js which leads to the search-page
- [ ] you can copy the search function of the "pfand"-page and refactor it
- [ ] the edit page should pick a customer dynamically and lead to a form 
- [ ] add the UPDATE request to the form to change the data in the database

**Comment by Miladu93** [comment]
looks good to me
