### ISSUE TITLE
US 2 -Navigation Bar

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#2]
## Value Proposition

As a User i want to have a nice overview of 
the pages of the app 
in order to navigate through the app
​

## Description

<img width="204" alt="Bildschirmfoto 2023-07-19 um 11 07 56" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/6ee73ae0-bff1-47e5-99e3-8c119b84fdf5">

​

## Acceptance Criteria

- [x] there should be a navigation bar
- [x] the navigation bar contains a link to "Pfand", "Liste" and "Menü"
- [x] the links should navigate to the corresponding pages
- [x] the navigation bar should be aviable on every page and always be visible

## Tasks

- [x] create a branch with a fitting name
- [x] create the links
- [x] add the links to the navigation
- [x] add pages with proper names for the different contents and make the links navigate to the corresponding pages
- [x] make sure the navigation has a fixed positioning and add it to the global components

**Comment by FlorianNova** [comment]
create a Task were the links for the navigation are created. create the Task were the pages are created.
switch Tasks to a logical order.

maybe add checkboxes like in US 1.
