### ISSUE TITLE
US10 - Add customer info

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#20]
## Value Proposition
As a user 
i want to see some customer information
in order to know where to put the flowerboxes

## Description

​
<img width="293" alt="Bildschirmfoto 2023-07-25 um 16 39 58" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/baef0388-d67e-4daa-b1da-3b41c9577ba4">

## Acceptance Criteria

- [ ] there should be a customer info in the add-deposit page 
- [ ] the customer info should be editable by clicking on a button
- [ ] clicking the button makes the customer area to an input and lets the button turn to a submit button
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] add a costumer info key to the  model
- [ ] let the customer data be displayed below the save and cancel button
- [ ] add the edit button which calls an modal with an input to change the info

**Comment by FlorianNova** [comment]
lgtm
