### ISSUE TITLE
US 11 - Add stock functionality

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#21]
## Value Proposition

As a user
i want to see how much boxes are in stock
to know how much boxes i have for deliveries
​

## Description
<img width="621" alt="Bildschirmfoto 2023-07-25 um 16 55 43" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/f5950413-9db4-4ccd-a57d-30e0e5aad9f1">

## Acceptance Criteria

- [ ] there should be a button in the menu with "Lagerbestand" as text
- [ ] clicking on the modal should open a modal showing how much boxes are in stock
- [ ] when you add boxes to a customer, the stock should change

      ​

## Tasks

- [ ] add a new collection in the database called "stock", it should save a single number of boxes in stock
- [ ] add the funcitonality to handleSave, which decreases the stock when there are boxes delivered to a customer
- [ ] add the button to the menu and the modal which shows the stock

**Comment by FlorianNova** [comment]
lgtm too
