### ISSUE TITLE
US 12 - Add timestamp

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#23]
## Value Proposition

As a user
i want to see when there where sombody for the last time at a customer,
to see if i should pick up the boxes, in case the customer is not going to order again, 
​

## Description

![Bildschirmfoto 2023-07-26 um 12 01 08](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/22f5f60e-1cf3-4d41-8b37-93d0f2f1ba4f)

​

## Acceptance Criteria

- [ ] there should be a last-delivery-date  shown in the list 
- [ ] the date should change, if somebody adds boxes to a customer 
      ​

## Tasks

- [ ] add a timestamp key to the Customer model (required:false)
- [ ] add a timestamp functionality to the handleSave function which sends a "PUT" request to the database and changes the data in the database
- [ ] change the list-page, so that it shows the date too

**Comment by Roland-Hufnagel** [comment]
LGTM. Clear and useful US!
