### ISSUE TITLE
US13 - Add cloudinary upload

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#28]
## Value Proposition

As a User 
i want to be able to upload images
in order to let other users know where to store the flowers.
​

## Description
![Bildschirmfoto 2023-07-28 um 15 17 31](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/7c3a2c95-4012-43af-8868-9d6ea42bc066)

​

## Acceptance Criteria

- [ ] there is an upload input on the deposit page
- [ ] if you upload an image its displayed and there is a button to edit the image

## Tasks

- [ ] create a branch with a fitting name
- [ ] create a cloudinary access
- [ ] add the cloudinary connection to your project
- [ ] add the upload input to your deposit page
