### ISSUE TITLE
US15 - Add Map

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#31]
## Value Proposition

As a user
I want to have a map to see all my customers locations
in order to see where i could pick the most boxes on my route.
​

## Description

![Image](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/4af1d1bb-8c6d-4e5a-b6ac-12b5874b3ae2)

​

## Acceptance Criteria

- [ ] the menu contains a new button leading to a map
- [ ] the map shows the location of all customers
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] add proper location data to the customers
- [ ] add a map using open street map to display the customers stores 
- [ ] add a button to the menu which opens the map
