### ISSUE TITLE
US14 - Add Navigation link

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#33]
## Value Proposition

As a user
I want to have a Link to start a navigation to my customer
In order to have a quick navigation without putting all the data into google maps manually.
​

## Description
![Bildschirmfoto 2023-08-02 um 12 15 10](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/df6a244a-4ed6-4363-b6ee-44c8c70ffdbd)

​

## Acceptance Criteria

- [ ] there is a link called "Navigation" in the deposit-page
- [ ] the link starts a google maps navigation to the customers store
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] use the customer data to build a google maps link
- [ ] create a button/link refering to the google maps navigation

**Comment by CJAkkuec** [comment]
> create a branch with a fitting name

I'd probably just mention the branch name right in the tasks, seeing as how it's your "job" as the person who writes the user stories to make sure that the developer sticks to e.g. an established naming convention.
