### ISSUE TITLE
US 16 - Refactoring and Styling

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#34]
## Value Proposition

As a user
I want to have a nice styling and performance for the App im using 
​

​

## Acceptance Criteria

- [ ] there are props for styled components in use
- [ ] components are more reusable
- [ ] the folder structure should be logical and understandable

## Tasks

- [ ] create a branch with a fitting name
- [ ] build styled components with props for e.g. buttons
- [ ] sort your folders in an understandable way

**Comment by CJAkkuec** [comment]
Very strictly speaking, this is a developer task, not a user story - so essentially a regular ticket.
YMMV depending on the coach, but as far as I'm concerned we don't require students to write user stories for non-feature developer tasks such as refactoring. You'd forego including the Value Proposition and Acceptance Criteria and simply list your tasks.
