### ISSUE TITLE
US 20 - Authentification

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#37]
## Value Proposition
As a user 
i want to be able to log myself in
so i can see how much entrys ive made and check if i have forgot a customer.
​

## Description

![Bildschirmfoto 2023-08-04 um 09 23 29](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/9e5705dd-2c67-4b15-b2d1-45ac1139cc11)

​

## Acceptance Criteria

- [ ] There is a login to authentify the users
- [ ] only the admin can delete customers
- [ ] if youre not logged in you dont have any access to the data
      ​

## Tasks

- [ ] Create a branch called "feature/authentification"
- [ ] Add an authentification via credentials
- [ ] let only the admin be able to delete customers
- [ ] drivers/test users can do everything else and withoud a login you cant access data through the server

**Comment by ekat-br** [comment]
LGTM :)
