### ISSUE TITLE
US 16 - Add different markers to map

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#39]
## Value Proposition

As a user
i want to have different coloured markers depending on when the customer got the last delivery
in order to see where i should pick up the boxes, or generally ask them why they dont order anymore. 
​

## Description
<img width="356" alt="Bildschirmfoto 2023-08-05 um 15 58 52" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/f049265e-9a41-480b-8de8-571b572ecb70">

​

## Acceptance Criteria

- [ ] On the map, the markers should be styled in red, yellow and green
- [ ] the color should depend on when the customer got the last delivery
- [ ] there should be an icon showing how much boxes are at the customers store
      ​

## Tasks

- [ ] add a function, which gets the difference of days between and day and the last entry of boxes/delivery
- [ ] add a red, yellow and green marker to the map
- [ ] add an if functionality, which sets the markers in the corresponding color depending on the last delivery
- [ ] add an icon, which is shown if the boxes at the customer are higher than 10

**Comment by Bilal4317** [comment]
lgtm
