### ISSUE TITLE
US 4 - Add counters for boxes/buckets

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#4]
## Value Proposition

As a user
I want to have an interface to count the
boxes/buckets i have delivered/received
in order to add them to the customer data in the list

## Description

![Bildschirmfoto 2023-07-19 um 14 23 03](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/38109b91-2d9a-4940-84fe-553c20d5d545)

​

## Acceptance Criteria

- [ ] there should be the name of the customer displayed
   as a heading
- [ ] there should be 4 counters to set how much boxes/buckets
   you have delivered/received
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] add a new component, which dynamically searchs for 
the customer-id ([id].js) 
- [ ] it should display the customer name as an h2
- [ ] add 4 states, one for each counter
- [ ] for each counter display the actual count and an 
add and subtract button

**Comment by Roland-Hufnagel** [comment]
Thats a good story. But I am wondering that you have a navigation at this point and saw that the navigation was your second userstory. For the future I recommend to make the navigation later, when you really have to switch between pages.
