### ISSUE TITLE
US 18 - Add bucket attachments

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#41]
## Value Proposition

As a user,
i want to be able to count attachements of the buckets too,
in order to add them to the customer stock.
​

## Description

<img width="260" alt="Bildschirmfoto 2023-08-07 um 19 57 52" src="https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/89861257-7d0b-41c0-9f93-6e1551b1ae66">

​

## Acceptance Criteria

- [ ] there should be a possibilty to add attachments to the customer
- [ ] the list should show the attachments

## Tasks

- [ ] add the different attachments to the db model
- [ ] add a counter state for the attachments
- [ ] update the POST request in the handleSave function
- [ ] update the list component and add an extended mode if the table view gets to confusing

**Comment by Roland-Hufnagel** [comment]
Looks good 🚀

**Comment by mbosselmann** [comment]
Hi Johannes,
Roland approved your US yesterday, but I think as the title of your user story changed this is an update? :) 
I only have one remark: You write in your value proposition that the user wants to count attachments of the bucket but in your acceptance criteria you do not mention that you want to count attachments ("there should be a possibilty to add attachments to the customer"). This was slightly confusing for me. Therefore, I would suggest to describe more what you mean with your first acceptance criterion. :) For example:

- there should be a possibility to add attachments for each customer
- there are two buttons: one to increment the amount of attachments and one to decrement the amount of attachments

I hope this does help! Feel free to ask if you have further questions. :)
