### ISSUE TITLE
US19 - Add Error Modals

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#43]
## Value Proposition

As a user
i want to be informed if something didnt work
in order to find another solution or try it again.

## Description
![Bildschirmfoto 2023-08-09 um 08 58 07](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/2fe422f8-4481-4ff3-8724-6603c78283ec)

​

## Acceptance Criteria
- [ ] If you push the form button, and the API cant relate any position (longitude, latitude) to it, there should popup a modal which tells the user, that there was no location added to the customer
- [ ] if everything worked fine, there should be a small model in the corner too
- [ ] Same should happen in the edit form
- [ ] If deposit cant be added there should be a modal too, also if it was added successfull, there should be a small modal

      ​

## Tasks

- [ ] build modal styles for the reasons
- [ ] let the modals be displayed, if the mentioned errors occure/ everything was sucessfull

**Comment by mbosselmann** [comment]
LGTM! 👍 But something went wrong while formatting this user story. :)
And a good nice to have would be to see the described acceptance criteria in your wireframes as well. As if I did understand it correctly only one example of this modal that you want to use multiple times is shown.
