### ISSUE TITLE
US 5 - Add save and cancel button

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#5]
## Value Proposition

As a user
i want to have a save and cancel button
in order to save the boxes i have delivered/
received to the customer data or cancel the 
process.
​

## Description

![Bildschirmfoto 2023-07-19 um 14 28 02](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/c82aa034-3311-4158-93b8-3b2e984213c3)

​

## Acceptance Criteria

- [ ] there should be a proper styled save and cancel button
- [ ] if you use the save button, the delivered/ received boxes/buckets should be subtractet and the result should be added to the customer data
- [ ] if you use the save button it should navigate you back to the default "Pfand"-page
      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] in the app js create a state with an initialize value of the dummyArray
- [ ] add the save button to the [id].js with a  function, which adds the counter-data to the  customer-data
- [ ] add the cancel button to, which is a link to the "Pfand"-page

**Comment by FlorianNova** [comment]
lgtm
