### ISSUE TITLE
US 6 - Add database to the project

### ISSUE THREAD

**Issue by HannesOster** [HannesOster/capstone_flower_box_deposit_app#6]
## Value Proposition
As a user 
i want to use a databse
to achieve my data from different devices
​

## Description

![Bildschirmfoto 2023-07-19 um 14 37 36](https://github.com/HannesOster/capstone_flower_box_deposit_app/assets/128285488/71ee6528-ecbf-4df1-88a0-74d011e69dc2)

​

## Acceptance Criteria

- [ ] there should be a database for the costumer data
- [ ] the data for the list component is given by a database
- [ ] the "Pfand"-page functionality should  add the data to the database      ​

## Tasks

- [ ] create a branch with a fitting name
- [ ] Create a database in mongoDB(for first it would be enough to have some example data in it)
- [ ] create a connect.js
- [ ] create the model for the data
- [ ] the list component should send a READ request to the database and display the data
- [ ] in the [id].js should be a PUT request and the data of the counters should be added to the data after pushing the save button

**Comment by FlorianNova** [comment]
lgtm
